[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  
  #base = "/frontend/simple"
  #base = "/"

[context.production.environment]

  REACT_APP_MAG_REST = "https://author-td8tdv78a6qyzt6p.saas.magnolia-cloud.com/.rest/delivery/tech"
  REACT_APP_MAG_REST_HANDS = "https://author-td8tdv78a6qyzt6p.saas.magnolia-cloud.com/.rest/delivery/hands"

  REACT_APP_MAG_REST_NODES = "https://author-td8tdv78a6qyzt6p.saas.magnolia-cloud.com/.rest/environments/cards/nodes/v1"