layout:
  groups:
    - name: act_group
       label: Activities
       apps:
            - name: activities-app
  rows:
    - name: three
      groups: !override
        custom: custom
        recommend: act_group