site:

 # This will take effect on COMMUNITY EDITION 
  cors:
    default:
      uris:
        rest:
          patternString: /.rest/*
      allowedOrigins:
        all: '*'
      allowedMethods:
        all: '*'
      allowedHeaders:
        all: '*'

  theme:
    name: travel-demo-theme

  i18n:
    class: info.magnolia.cms.i18n.DefaultI18nContentSupport
    enabled: true
    fallbackLocale: en
    locales:
      en:
        country: ''
        enabled: true
        language: en
      de:
        country: ''
        enabled: true
        language: de